### ISSUE TITLE
Standardize input/output file names for categorizers

### ISSUE THREAD

**Issue by mrose17** [starsnotinjars/Automatic-Website-Categorizers#2]
i'd like to see `extract3.py` and `descr3.py` use the same filename for input, e.g., `publisherIDs.txt`

i'd also like to see them both be able to read the filename from the command line, e.g.,

      python3 extract3.py -i sites.txt -o output.txt

**Comment by starsnotinjars** [comment]
Hi Marshall,

The program descr3.py has the ability to read the input file name from the command line if one is specified. If one is not specified, the name of the input file will default to websites.txt. The user must type a '>' symbol with the name of the output file in the command line to tell the program where to dump the results.

Example: 
python descr3.py websites.txt >output_from_descr.txt

The program extract3.py uses the results from the GoogleScraper program. GoogleScraper and descr3.py both process an input file called websites.txt. Therefore, the input file of extract3.py can't have the same name as descr3.py. I modified extract3.py so that one can enter the input filename (same name as the output filename that one gave the GoogleScraper program) on the command line right after 'extract3.py' and the the output of this program will go into the filename that is specified after this. I updated the branch readme file with the new instructions.

Example: 
GoogleScraper -m http -s "bing" --keyword-file websites.txt > output.txt
python extract3.py output.txt output_from_extract.txt

Please let me know if you want me to make any more changes to the way that filenames are input to the programs or named.

**Comment by mrose17** [comment]
thanks. our goal is to get the work flow set up so that there aren't any manual steps other than creating the input file. let's standardize on websites.txt as the input file name and format for all of the categorizer.

**Comment by starsnotinjars** [comment]
Hi Marshall, I eliminated the manual steps from the description searcher. I will eliminate all manual steps from the title searcher program soon.

**Comment by mrose17** [comment]
excellent, thanks!

**Comment by mrose17** [comment]
OBE
