### ISSUE TITLE
"standard" names for categories

### ISSUE THREAD

**Issue by mrose17** [starsnotinjars/Automatic-Website-Categorizers#9]
@starsnotinjars - hi.

1. if you look at https://github.com/brave/ledger-publisher/tree/master/categories you'll see the "standard" names for the categories. spelling and capitalization is important (e.g., "imageStores"). going forward, please use those values in the output from the categorizers.

2. what is the "News" category? should those be excuded or ignored?

3. with the exception of the "News" category, i have updated the database using the new description file you sent me. thanks!

**Comment by starsnotinjars** [comment]
1. OK I will do this.
2. The News category, as we discussed, is any website that contained any of the they keyword 'news', 'weather', or 'latest stories'. The flagging the news sites is to create an inclusion list that we can check our exclusion list against. 
3. You're welcome!

**Comment by starsnotinjars** [comment]
I finished task #1 for the tittles searcher and the description searcher program. I didn't do it yet for the aggregator finder program because that is still a work in progress. We still need to come to agreement about which aggregators we want to block and which we don't. There has been discussion about using  the ratio of content to ad space but this needs to be discussed more.

**Comment by mrose17** [comment]
ok, let's resolve this with @bsclifton and later today.

**Comment by mrose17** [comment]
OBE
